name: Notify on changes
on:
  push:
    branches:
      - main
    paths:
      - '/hanafuda/video-games.md'

jobs:
  hawk:
    name: hawk
    runs-on: ubuntu-latest
    
    steps:
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEB_HOOK }}
        slack_message: '#fudawiki change /hanafuda/video-games.md'
