name: fetch upstream

on: 
  schedule:
    - cron: "10 13 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch upstream
      uses: 135e2/sync-upstream-repo@v0.1.5
      with:
      #Git upstream repo
        upstream_repo: https://github.com/Shotbow/fudawiki-files.git
        upstream_branch: master
        local_branch: master
	github_token: ${{ secrets.GITHUB_TOKEN }}
